print(12/(1+2)+2**2)
print("masum6 al mahamud")
print("I am reading")
print("I am reading")
print("I am reading")
print("I am reading")
print("I am reading")
print("I am reading")
print("masum6 al mahamud")
print("I am reading")
print("I am reading")
print("I am reading")
print("I am reading")
print("I am reading")
print("I am reading")